---
name: concourse

# replace with bosh status --uuid
director_uuid: 7c2f2dab-572c-4234-8b1c-6b7baeb3d818

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

# pick a sane db name and password
atc_db_name: &atc-db-name atc
atc_db_role: &atc-db-role
  name: admin # replace
  password: admin # replace

networks:
- cloud_properties: {}
name: floating
type: vip
- cloud_properties:
  name: anynines
  net_id: f00f560e-4a58-4d02-b8db-562d6332caf6
  security_groups:
  - cf-private
  - default
name: default
type: dynamic

disk_pools:
- name: database-disk-pool
  disk_size: 20480
  cloud_properties:
    type: EMC-ThinVolume

- name: 2GB
  disk_size: 2048
  cloud_properties:
    type: EMC-ThinVolume

resource_pools:
- name: small
  network: default
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m1.small

- name: medium
  network: default
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m1.medium

# networks:
# - name: floating
#     type: vip
#     cloud_properties: {}
# 
#   - name: concourse
#     type: manual
#     subnets:
#       - range: 10.0.16.0/20
#         reserved: [10.0.16.2 - 10.0.16.9]
#         static:
#           - &discovery_static_ip 10.0.16.10
#         dns: [10.0.0.2]
#         gateway: 10.0.16.1
#         cloud_properties:
#           security_groups: [REPLACE_WITH_INTERNAL_SECURITY_GROUP_NAME]
#           subnet: REPLACE_WITH_INTERNAL_SUBNET



jobs:
  - name: discovery
    instances: 1
    resource_pool: discovery
    persistent_disk_pool: 2GB
    templates:
      - release: concourse
        name: consul-agent
    networks:
      - default:
        - dns
        - gateway
        name: default
      - name: floating
        static_ips:
        - 78.109.62.174 # replace
    properties:
      consul:
        agent:
          mode: server

  - name: web
    instances: 1
    resource_pool: web
    templates:
      - release: concourse
        name: consul-agent
      - release: concourse
        name: tsa
      - release: concourse
        name: atc
    networks:
      - default:
        - dns
        - gateway
        name: default
      - name: floating
        static_ips:
        - 78.109.62.175 # replace
    properties:
      atc:
        basic_auth_username: admin # replace
        basic_auth_password: admin # replace
        postgresql:
          database: *atc-db-name
          role: *atc-db-role

      tsa:
        atc:
          username: admin # replace
          password: admin # replace

      consul:
        agent:
          servers: {lan: [78.109.62.174]}

  - name: db
    instances: 1
    resource_pool: databases
    persistent_disk_pool: database-disk-pool
    templates:
      - release: concourse
        name: consul-agent
      - release: concourse
        name: postgresql
    networks: [{name: default, default: [dns,gateway]}]
    properties:
      postgresql:
        databases: [{name: *atc-db-name}]
        roles: [*atc-db-role]

      consul:
        agent:
          servers: {lan: [78.109.62.174]}

  - name: worker
    instances: 1
    resource_pool: medium
    templates:
      - release: concourse
        name: consul-agent
      - release: concourse
        name: groundcrew
      - release: garden-linux
        name: garden
    networks: [{name: default, default: [dns,gateway]}]
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

      consul:
        agent:
          servers: {lan: [78.109.62.174]}

compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.medium

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000